export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';

export const ARRIVALS_LOADING = 'ARRIVALS_LOADING';
export const ARRIVALS_FAILED = 'ARRIVALS_FAILED';
export const ADD_ARRIVALS = 'ADD_ARRIVALS';

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';