export const INCREMENT_CART = INCREMENT_CART;
export const DECREMENT_CART = DECREMENT_CART;
export const REMOVE_CART = REMOVE_CART;
export const CLEAR_CART = CLEAR_CART;
export const TOTAL_CART = TOTAL_CART;
export const CART_TAX = CART_TAX;
export const CART_SUB_TOTAL = CART_SUB_TOTAL;